"""SEC filing ingestion pipeline CLI.

Orchestrates Docling chunking, Gemini text-embedding-004 embedding generation,
and Supabase Postgres vector storage. Includes safe 1-chunk verification mode.
"""

from __future__ import annotations

import argparse
import sys
import time
from pathlib import Path
from typing import Any

# Ensure UTF-8 output on Windows
if sys.platform == "win32":
    sys.stdout.reconfigure(encoding="utf-8")

import structlog

from app.database.documents import (
    bulk_insert_chunks,
    delete_chunks_by_document,
    get_chunk_count,
    list_source_documents,
    search_chunks_vector,
)
from app.ingest.chunker import FilingChunker
from app.ingest.embedder import GeminiEmbedder

logger = structlog.get_logger(__name__)

REPO_ROOT = Path(__file__).resolve().parent.parent.parent.parent
DATA_DIR = REPO_ROOT / "data"
MARKDOWN_DIR = DATA_DIR / "markdown"


def run_one_chunk_test() -> bool:
    """Safely test chunking, Gemini embedding, and pgvector storage for exactly 1 chunk."""
    print("\n========================================================")
    print("Running Single Chunk Verification Test")
    print("========================================================\n")

    # 1. Fetch any source document from DB
    docs = list_source_documents()
    if not docs:
        print("✗ ERROR: No source documents found in database. Run data/load_source_documents.py first.")
        return False

    sample_doc = docs[0]
    ticker = sample_doc["ticker"]
    year = sample_doc["fiscal_year"]
    doc_id = sample_doc["id"]
    local_path = sample_doc.get("metadata", {}).get("local_path")

    print(f"1. Target Document: {ticker} ({year}) [ID: {doc_id}]")
    md_path = MARKDOWN_DIR / Path(local_path.replace("\\", "/"))

    # 2. Chunk document with Docling
    print("2. Chunking with Docling HybridChunker (max_tokens=600)...")
    chunker = FilingChunker(max_tokens=600)
    chunks = chunker.chunk_file(
        md_path,
        ticker=ticker,
        fiscal_year=year,
        company_name=sample_doc["company_name"],
        document_id=doc_id,
    )

    if not chunks:
        print("✗ ERROR: No chunks generated by chunker.")
        return False

    test_chunk = chunks[0]
    print(f"   ✓ Chunks generated: {len(chunks)} total")
    print(f"   ✓ Selected Chunk 0 | Section: {test_chunk['section']} | Estimated tokens: {test_chunk['token_count']}")
    print(f"   --- Preview ---\n{test_chunk['chunk_text'][:200]}...\n----------------")

    # 3. Generate 1 Gemini embedding
    print("3. Generating 1 vector embedding with Gemini (text-embedding-004)...")
    embedder = GeminiEmbedder()
    embedding = embedder.embed_text(test_chunk["chunk_text"])

    if not embedding:
        print("✗ ERROR: Failed to get embedding from Gemini.")
        return False

    dim = len(embedding)
    print(f"   ✓ Embedding generated successfully! Vector dimension: {dim} (Expected: 768)")
    if dim != 768:
        print(f"✗ ERROR: Vector dimension mismatch: {dim} != 768")
        return False

    test_chunk["embedding"] = embedding

    # 4. Insert 1 chunk into database
    print("4. Inserting chunk into Supabase document_chunks table...")
    # Delete existing test chunk if present
    delete_chunks_by_document(doc_id)
    inserted = bulk_insert_chunks([test_chunk])
    print(f"   ✓ Inserted {inserted} chunk into Postgres")

    # 5. Test vector similarity query against pgvector
    print("5. Testing pgvector cosine similarity search...")
    search_results = search_chunks_vector(embedding, limit=1, ticker=ticker)

    if not search_results:
        print("✗ ERROR: Vector search returned 0 results.")
        return False

    top_match = search_results[0]
    print("   ✓ Search returned match:")
    print(f"     - Similarity score: {top_match['similarity']:.4f} (Distance: {top_match['distance']:.4f})")
    print(f"     - Chunk section: {top_match['section']}")
    print(f"     - Ticker & Year: {top_match['ticker']} {top_match['fiscal_year']}")

    print("\n========================================================")
    print("✓ SINGLE CHUNK VERIFICATION TEST PASSED 100%!")
    print("✓ Docling chunking, Gemini embeddings, and pgvector storage are fully operational.")
    print("========================================================\n")
    return True


def run_ingestion_pipeline(
    ticker: str | None = None,
    fiscal_year: int | None = None,
    force: bool = False,
    batch_size: int = 50,
) -> dict[str, Any]:
    """Run full corpus ingestion across source documents."""
    docs = list_source_documents(ticker=ticker, fiscal_year=fiscal_year)
    total_docs = len(docs)
    print(f"Found {total_docs} source document(s) matching criteria.\n")

    chunker = FilingChunker(max_tokens=600)
    embedder = GeminiEmbedder(batch_size=batch_size)

    total_chunks_inserted = 0
    start_time = time.time()

    for idx, doc in enumerate(docs, start=1):
        doc_id = doc["id"]
        doc_ticker = doc["ticker"]
        doc_year = doc["fiscal_year"]
        company_name = doc["company_name"]
        local_path = doc.get("metadata", {}).get("local_path")

        # Check if chunks already exist
        existing_chunks = get_chunk_count(doc_id)
        if existing_chunks > 0 and not force:
            print(f"[{idx:02d}/{total_docs:02d}] Skipped: {doc_ticker} ({doc_year}) already has {existing_chunks} chunks.")
            total_chunks_inserted += existing_chunks
            continue

        md_path = MARKDOWN_DIR / Path(local_path.replace("\\", "/"))
        if not md_path.exists():
            print(f"[{idx:02d}/{total_docs:02d}] WARNING: File not found: {md_path}. Skipping.")
            continue

        print(f"[{idx:02d}/{total_docs:02d}] Processing {doc_ticker} ({doc_year})...")
        t0 = time.time()

        # 1. Chunk document
        chunks = chunker.chunk_file(
            md_path,
            ticker=doc_ticker,
            fiscal_year=doc_year,
            company_name=company_name,
            document_id=doc_id,
        )

        chunk_count = len(chunks)
        print(f"       -> Generated {chunk_count} chunks with Docling")

        # 2. Generate embeddings in batches
        texts_to_embed = [c["chunk_text"] for c in chunks]
        embeddings = embedder.embed_batch(texts_to_embed)

        for chunk_dict, emb in zip(chunks, embeddings, strict=True):
            chunk_dict["embedding"] = emb

        # 3. Store in database
        if force and existing_chunks > 0:
            delete_chunks_by_document(doc_id)

        inserted = bulk_insert_chunks(chunks)
        elapsed = time.time() - t0
        print(f"       ✓ Ingested {inserted} chunks + embeddings in {elapsed:.1f}s")
        total_chunks_inserted += inserted

    total_time = time.time() - start_time
    print("\n========================================================")
    print("Ingestion complete!")
    print(f"Total chunks stored in database: {total_chunks_inserted}")
    print(f"Total time: {total_time / 60:.2f} minutes")
    print("========================================================\n")

    return {"total_chunks": total_chunks_inserted, "documents_processed": total_docs}


def main():
    parser = argparse.ArgumentParser(description="SEC Filing Chunking and Vector Ingestion Pipeline")
    parser.add_argument("--test-one-chunk", action="store_true", help="Run safe single-chunk verification test")
    parser.add_argument("--ticker", type=str, default=None, help="Filter by ticker (e.g. AAPL)")
    parser.add_argument("--year", type=int, default=None, help="Filter by fiscal year (e.g. 2024)")
    parser.add_argument("--force", action="store_true", help="Force re-chunking and re-embedding")
    parser.add_argument("--batch-size", type=int, default=50, help="Embedding batch size (default: 50)")

    args = parser.parse_args()

    if args.test_one_chunk:
        success = run_one_chunk_test()
        sys.exit(0 if success else 1)

    run_ingestion_pipeline(
        ticker=args.ticker,
        fiscal_year=args.year,
        force=args.force,
        batch_size=args.batch_size,
    )


if __name__ == "__main__":
    main()
